name: mergeday

services:
  sql:
    image: postgres:15-alpine
    container_name: mergeday-sql
    environment:
      - POSTGRES_PASSWORD=Passw0rd_Strong_123!
      - POSTGRES_DB=MergeDayDb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: src/MergeDay.Api/Dockerfile
    container_name: mergeday-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MergeDayDb=Host=sql;Database=MergeDayDb;Username=postgres;Password=Passw0rd_Strong_123!;
    depends_on:
      sql:
        condition: service_healthy

  client:
    build:
      context: ../src/MergeDay.Client
      dockerfile: Dockerfile
    container_name: mergeday-client
    ports:
      - "5001:80"
    environment:
      API_URL: http://localhost:5000
    depends_on:
      - api

volumes:
  pgdata:
