name: mergeday-sql

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mergeday-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd_Strong_123!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Passw0rd_Strong_123!", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
volumes:
  mssql-data:
